name: Release

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    env:
      CGO_ENABLED: 0
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache: true
      
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Build for all platforms
        run: |
          platforms=("linux_amd64" "linux_arm64" "windows_amd64" "windows_arm64" "darwin_amd64" "darwin_arm64")
          
          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d '_' -f1)
            arch=$(echo $platform | cut -d '_' -f2)
            
            echo "Building for $os/$arch..."
            
            output_name="terraform-provider-containerregistry_v${VERSION}_${os}_${arch}"
            if [ "$os" = "windows" ]; then
              output_name="${output_name}.exe"
            fi
            
            GOOS=$os GOARCH=$arch go build -o "build/${output_name}" .
          done
      
      - name: Checkout gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git worktree add pages gh-pages

      - name: Setup Terraform Registry Builder
        run: |
          # Install terraform-registry-builder
          go install github.com/ikedam/terraform-registry-builder@latest
          
      - name: Build Terraform Provider Registry
        env:
          TFREGBUILDER_GPG_KEY: ${{ secrets.TFREGBUILDER_GPG_KEY }}
        run: |
          # Create registry directory if not exists
          mkdir -p pages/providers/ikedam
          
          # Build registry using terraform-registry-builder
          terraform-registry-builder ./build .pages/providers/ikedam
            
      - name: Commit and push gh-pages
        run: |
          cd pages
          git add .
          git commit -m "Update Terraform provider repository for v${VERSION}" || echo "No changes to commit"
          git push origin gh-pages
