name: Release

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# Set permissions at the workflow level
permissions:
  contents: write

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Use default shallow clone for the main branch

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create build directory
        run: mkdir -p build

      - name: Build for all platforms
        run: |
          platforms=("linux_amd64" "linux_arm64" "windows_amd64" "windows_arm64" "darwin_amd64" "darwin_arm64")

          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d '_' -f1)
            arch=$(echo $platform | cut -d '_' -f2)

            echo "Building for $os/$arch..."

            output_name="terraform-provider-containerregistry_v${VERSION}_${os}_${arch}"
            if [ "$os" = "windows" ]; then
              output_name="${output_name}.exe"
            fi

            # Set -buildvcs=false to avoid `error obtaining VCS status: exit status 128`
            GOOS=$os GOARCH=$arch docker compose run --rm go build -buildvcs=false -o "build/${output_name}" .
          done

      - name: Checkout gh-pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # Fetch only the gh-pages branch
          git fetch --depth=1 origin gh-pages:gh-pages
          git worktree add pages gh-pages

      - name: Build Terraform Provider Registry
        env:
          TFREGBUILDER_GPG_KEY: ${{ secrets.TFREGBUILDER_GPG_KEY }}
        run: |
          # Create registry directory if not exists
          mkdir -p pages/providers/ikedam

          # Build registry using terraform-registry-builder
          docker compose run --rm terraform-registry-builder ./build ./pages/providers/ikedam

      - name: Commit and push gh-pages
        run: |
          cd pages
          git add .
          git commit -m "Update Terraform provider repository for v${VERSION}" || echo "No changes to commit"
          git push origin gh-pages
